#!/usr/bin/env python

from __future__ import division
import dipy
import sys
import sklearn
import nibabel as nib


print("This is a test.")
print("Python version: %s" %sys.version)
print("Dipy version: %s" %dipy.__version__)
print("Sklearn version: %s" %sklearn.__version__)
print("Nibabel version: %s" %nib.__version__)

print("Loading example data...")
tract = nib.streamlines.load("data/track.tck")
print("Total number of streamlines of the tractogram: %i" %len(tract.streamlines))
print("Affine of the tractogram:\n %s" %tract.affine)
t1 = nib.load("data/t1.nii.gz")
print("Affine of the structural image:\n %s" %t1.affine)